002 view job spec
Jadevious/kainos-recruitment-api pull request #11
Opened 2022-10-06 14:31 UTC by Jadevious

Ticket: https://trello.com/c/h3r4cLz8

2022-10-06 15:05 UTC, Kirsten1822 requested changes

2022-10-06 15:05 UTC, Kirsten1822 commented on database.sql
> +specification varchar(255) NOT NULL,
Are we making responsibilities NOT NULL?

2022-10-06 15:07 UTC, Jadevious commented on database.sql
> +specification varchar(255) NOT NULL,
Responsibilities don't currently have any values in the insert statements in main, so the responsibility to add them for responsibilities falls outside of this ticket - allowing it to be null just to allow the inserts to work.

2022-10-06 15:08 UTC, Kirsten1822 approved these changes

2022-10-10 12:07 UTC, boydstepnew approved these changes

2022-10-11 14:14 UTC, merged